name: audits

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  audit-dependencies-on-laravel-10:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.1
          - 8.2
          - 8.3
        laravel:
          - "10.x"
        experimental:
          - false

    name: PHP${{ matrix.php }}-${{ matrix.os }} with Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, pdo_mysql, bcmath, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install Laravel ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --prefer-stable --no-cache"

      - name: Installed dependencies
        run: composer show -D

      - name: Audit dependencies
        run: composer audit

  audit-dependencies-on-laravel-9:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - '8.0'
          - 8.1
          - 8.2
        laravel:
          - "9.x"
        experimental:
          - false

    name: PHP${{ matrix.php }}-${{ matrix.os }} with Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, pdo_mysql, bcmath, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install Laravel ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --prefer-stable --no-cache"

      - name: Installed dependencies
        run: composer show -D

      - name: Audit dependencies
        run: composer audit

  audit-dependencies-on-laravel-8:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 7.3
          - 7.4
          - '8.0'
          - 8.1
        laravel:
          - "8.x"
        experimental:
          - false

    name: PHP${{ matrix.php }}-${{ matrix.os }} with Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, pdo_mysql, bcmath, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install Laravel ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --prefer-stable --no-cache"

      - name: Installed dependencies
        run: composer show -D

      - name: Audit dependencies
        run: composer audit
